all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: ansible
test:
  hosts:
    vm1:
      ansible_host: 192.168.1.240
pre_prod:
  hosts:
    vm2:
      ansible_host: 192.168.1.52
